
title: My Academic Website
description: Personal site with research, projects, and other interests.
baseurl: ""
url: "https://<username>.github.io"
markdown: kramdown
theme: jekyll-theme-minimal
author: Your Name
year: 2025
