
title: Anurag Pendse
description: A small peek into my rather uninteresting life :)
baseurl: ""
url: "https://AnuragPendse.github.io"
markdown: kramdown
theme: jekyll-theme-minimal
author: Your Name
year: 2025
